### ISSUE TITLE
 Mixin --app-header-background-front-layer for applying a background image

### ISSUE THREAD

**Issue by aglusk** [PolymerElements/app-layout#237]
Setting a background image on the app header bar appears to be broken.
Or, if additional steps are needed, perhaps update docs?
app-header {
  --app-header-background-front-layer: {
        background-image:  url("");
  };
}

Specifying : 
  "app-layout": "polymerelements/app-layout#0.9.0",

Clears up the issue as a temporary workaround.

**Comment by frankiefu** [comment]
If you are not setting any background effects (e.g. `effects="blend-background parallax-background"`) and you just want to set a background image on the `app-header`, then you can just set it on the `app-header` itself instead of using the mixin.
```
app-header {
  background-image: url(//app-layout-assets.appspot.com/assets/bg1.jpg);
  background-position: left center;
  background-size: cover;
}
```

In app-layout#0.9.1, we made an optimization so the background div's are not created unless you are using background effects.

**Comment by aglusk** [comment]
I swear I tried that, at least 3 times. But now it's working that way. 
Thanks!
