### ISSUE TITLE
Drawer Toggle not working as expected (as in docs)

### ISSUE THREAD

**Issue by bakku** [PolymerElements/app-layout#252]
### Description

When using a paper icon as the drawer toggle like stated in the docs (https://elements.polymer-project.org/elements/app-layout?active=app-drawer-layout#property-drawer) the paper icon does not display at all.

### Expected outcome
Paper icon displays and I can use it as a drawer toggle.

### Actual outcome
Paper icon does not display at all. No drawer toggle button available.

### Example Code
http://pastebin.com/VYbnBnrB

### Steps to reproduce
1. Take code from Pastebin
2. Use it in a polymer example project
3. polymer serve --open

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by keanulee** [comment]
The `drawer-toggle` only appears on narrow viewports where the drawer is not shown side-by-side with the content. When the drawer is opened side-by-side, `drawer-toggle` is hidden.

**Comment by motss** [comment]
In addition to that, you can set `force-narrow` on the `app-drawer-layout` for toggle drawer on wide layout. 

```
  <app-drawer-layout force-narrow>
     ...
  </app-drawer-layout>
```

**Comment by bobtista** [comment]
motss, the documentation shows the property as forceNarrow... ah crap I just realized that you can't use property names in the tags, you need to use dashes instead of camelcase. Attributes vs properties. It would be nice if the documentation just listed both, and showed examples of both. Anyway, yes, force-narrow works and forceNarrow doesn't.
