### ISSUE TITLE
Breaking changes in PATCH version v0.9.2!!!

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/app-layout#271]
API breaking changes does not belong to PATCH version!!!

https://github.com/PolymerElements/app-layout/releases/tag/v0.9.2

# Semantic Versioning 2.0.0

Given a version number **MAJOR.MINOR.PATCH**, increment the:

1. **MAJOR version** when you make **incompatible API changes**,
2. **MINOR version** when you add functionality in a backwards-compatible manner, and
3. **PATCH version** when you make backwards-compatible bug fixes.

http://semver.org

**Comment by JosefJezek** [comment]
FYI @robdodson

**Comment by motss** [comment]
This element is meant for breaking stuffs. Not surprised at all, I would say.

**Comment by abdonrd** [comment]
More information here: https://github.com/PolymerElements/app-layout/commit/97ac0d97570ccb0e010dc7c4510bfdd8d99b9f77#commitcomment-18184231

**Comment by frankiefu** [comment]
> ## Semantic Versioning Specification (SemVer)
> 
> 4\. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.


Afaik, there is no hard rules on versioning around breaking changes for prerelease (0.y.z).  Versioning rules (major/minor/patch) apply to **stable** public API.  Technically there is no *breaking changes* in prerelease since the public API is not yet finalized.  FWIW, we have been bumping [patch version](https://github.com/PolymerElements/app-layout/releases/tag/v0.0.14) for any changes in app-layout.

Right now the app elements are in prerelease (0.9.x).  We would like to move to 1.0 soon to lock down the public API and only then we can have version number dependent on this public API and how it changes.

Having said that, we know many people are relying on app-layout in theirs apps.  We have been trying to document all the changes between releases in the release notes.  And if people feel using minor version to indicate API changes in prerelease would help them to stabilize their apps, we could try to bump the y in 0.y.z for major changes from now on.

**Comment by JosefJezek** [comment]
Thank you

**Comment by blasten** [comment]
As @frankiefu pointed out, app-layout is still under development. The changes we introduced are small and should make it very easy to upgrade. However, we have heard you and have tagged a breaking change `v0.10.0`. `0.9.2` is still available, but it's compatible with `0.9.1`.

To upgrade,  your bower dependency should look like:  `"app-layout": "~0.10.0"` That would mean that you would get all patches, but no breaking changes.

**Comment by abdonrd** [comment]
@blasten thanks! :)

**Comment by JosefJezek** [comment]
I am using `"app-layout": "0.9.x"`. @blasten Thank you
