### ISSUE TITLE
persistent app-drawer being closed by the "drawer-toggle" attribute

### ISSUE THREAD

**Issue by MitchReidNZ** [PolymerElements/app-layout#312]
### Description
The drawer-toggle attribute on links in an app-drawer cause the drawer to close when a link is clicked / tapped. 
This behavior is correct for a non-persistent drawer, however I think the persistent drawer should not close.
This is also discussed in the old repository (https://github.com/Polymer/app-drawer-template/issues/20)

### Expected outcome

The persistent drawer remains open. (eg, on Desktop browsers)
Non-persistent drawer closes. (eg, on a Mobile browser)

### Actual outcome

The drawer is closed for both persistent and non-persistent drawers.

### Added extra
I believe the only change required is updating /app-drawer-layout/app-drawer-layout.html:216 from:
if (target && target.hasAttribute('drawer-toggle')) {
to
if (target && target.hasAttribute('drawer-toggle') && !this.drawer.persistent) {

I would gladly submit a pull request, however I'm not sure how to build/run the tests.

**Comment by keanulee** [comment]
The intention is for `drawer-toggle` to be only accessible on narrow viewports (and hidden when the layout is not narrow and the drawer is persistent - see https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/app-drawer-layout.html#L133). I didn't know that users were using the attribute on items in the drawer that should close the drawer, but that shouldn't have worked anyways since those items _should_ be hidden by the referenced CSS rule (unless their styling override that).

**Comment by mercmobily** [comment]
I commented on the old ticket rather than this one...
Is there a "good" way to make sure that the app-drawer will toggle once a selection has been made *IF* it's off by default? (It would make no sense to do something like this in a desktop site...)

Sorry about the noise, I am a little confused about this issue and am presenting my app on Friday and...

**Comment by mercmobily** [comment]
BTW for the sake of my Friday pressy, I "fixed" it like this:

    <paper-menu on-tap="_paperMenuTapped" id="menu-main" on-iron-select="_selectionEvent" selected="[[page]]" attr-for-selected="name">

    ...
    _paperMenuTapped: function( e ){
        var drawer = this.$$('app-drawer')
        if( !drawer.persistent) drawer.toggle();
    },

I wonder if something like this should be in app-drawer directly...

**Comment by keanulee** [comment]
I think we'll just do what @MitchReidNZ initially suggested (`drawer-toggle` does not toggle persistent drawer) - it makes sense to reuse the attribute.

**Comment by mercmobily** [comment]
@keanulee  Sorry for the bother, when do you think you will tag this for release on bower? I am asking because I am supposed to be deploying an app today for a presentation, and want to know if I need to add "patch app-drawer-layout.html" to my TODO for the day :D Thank you!

**Comment by keanulee** [comment]
@mercmobily Just tagged a release; hopefully that works out for you :)
