### ISSUE TITLE
Closing the App Drawer Leaves A Blank Space

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/app-layout#339]
If you rotate your screen so that it now displays in landscape mode, and then attempt to close the drawer using the close method, a blank space is left on the screen where the drawer was.  The remainder of the screen does not move left as expected.

**Comment by keanulee** [comment]
If you're using `app-drawer-layout`, you should be toggling the `forceNarrow` property on `app-drawer-layout` instead of using `close()` on `app-drawer`. `app-drawer-layout` manages the drawer's opened state - by calling `close()` on `app-drawer` directly, `app-drawer-layout` doesn't see this change.

**Comment by phidias51** [comment]
ForceNarrow doesn't seem to work in landscape mode.  Basically what I'm expecting is that whenever you select an item from the menu in the drawer, the drawer should disappear.

**Comment by keanulee** [comment]
Please provide a repo in a new bug - see issue template
