### ISSUE TITLE
app-drawer: Scroller gets blocked when drawer is on the right side.

### ISSUE THREAD

**Issue by myuseringithub** [PolymerElements/app-layout#425]
When `app-drawer` is aligned right, the scroller of the page won't respond to clicks, as if the drawer element z-index hides it. 

## Right aligned - Scrolling gets blocked
![6rhykxn5bn](https://cloud.githubusercontent.com/assets/7758497/23716506/2e1991f6-0439-11e7-8bb4-6cf2dc9b7b6a.gif)

## Left aligned - Scrolling can be clicked.
![jxwzt6omd7](https://cloud.githubusercontent.com/assets/7758497/23716499/28d250f2-0439-11e7-849b-6522a0b164a1.gif)

_________________
Using Polymer 2.0-preview
```
<app-drawer id="drawer" slot="drawer" align="right" swipe-open="" position="left" style="transition-duration: 200ms; touch-action: pan-y;" persistent="" opened="">
        <app-toolbar>Title</app-toolbar>
</app-drawer>
```

**Comment by keanulee** [comment]
This is probably because the `swipe-open` attribute/property creates a pseudo-`::after` element next to the drawer (which overlaps that scrollbar):

![image](https://cloud.githubusercontent.com/assets/1319720/23718615/0275284a-03ed-11e7-8127-382ff9d6dd7a.png)

You should remove the `swipe-open` attribute.

**Comment by myuseringithub** [comment]
Yes, that's correct. I will add the attribute `swipe-open` only on mobile, to solve the issue with Desktop. Thanks
