### ISSUE TITLE
Center element in app-header-layout with has-scrolling-region

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#467]
### Description
Trying to center the <code>sticky</code> element so that it appears as a header of the card beneath it. Unfortunately the center of the <code>app-header</code> is off by 1/2 of the width of the scroll-bar. Can you think of some way I can get around it? Thanks.

### Expected outcome
Centers to match:

![image](https://cloud.githubusercontent.com/assets/971651/25536173/c5c972be-2c07-11e7-97b8-b553df76ab3e.png)

### Actual outcome

![image](https://cloud.githubusercontent.com/assets/971651/25536119/8a308e86-2c07-11e7-9857-cea4975690be.png)

### Live Demo
http://jsbin.com/guxeqobixo/edit?html,output

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
The content inside `card-head` and `card-body` are centered correctly.  The offset you are seeing is because `card-body` is inside a scrolling region which has a scrollbar. So the actual width of `card-body` is less than the width of `card-head`, and thus the center of the two are not the same. There are ways to offset the margin to account for the width of scrollbar but that's not ideal.

**Comment by govis** [comment]
Thank you for taking a look, I will try to find some workaround.
