### ISSUE TITLE
<app-header-layout>   this.getBoundingClientRect();   got 8px with unknow situation

### ISSUE THREAD

**Issue by hzmnet** [PolymerElements/app-layout#470]
rect = ClientRect {top: 8, right: 1358, bottom: 8, left: 8, width: 1350…}
![qq 20170504003256](https://cloud.githubusercontent.com/assets/5361750/25671205/ab9d33d6-3061-11e7-8aef-80e53ba90e86.png)
![qq 20170504003355](https://cloud.githubusercontent.com/assets/5361750/25671206/ab9f1ff2-3061-11e7-849f-5c57041b8249.png)

**Comment by hzmnet** [comment]
OK  I solve when I set like below.

* {
    margin: 0;
    padding: 0;
}

**Comment by frankiefu** [comment]
It's difficult to tell what's going on without more info like a reduced test case and the steps: https://github.com/PolymerElements/app-layout/blob/master/CONTRIBUTING.md#filing-issues

But I suspect in this case is caused by the default body's margin which is 8px. You should be able to just set `margin: 0` on the body like in this demo: https://github.com/PolymerElements/app-layout/blob/master/demo/demo2.html#L35

Please let us know if you still see the issue.
