### ISSUE TITLE
Drawer won't toggle and layout is collapsing in 2.0 release.

### ISSUE THREAD

**Issue by vedtam** [PolymerElements/app-layout#475]
scription

Clean Polymer 2.0 install, app-drawer-layout broken, drawer won't toggle. If set to `open` explicitly the _app-drawer-layout_ collapses.

Expected outcome:
The drawer should toggle and the main content should not be collapsed on the drawers content when the drawer is set to 'open'.

Screenshot:
<img width="833" alt="screen shot 2017-05-16 at 10 58 18 am" src="https://cloud.githubusercontent.com/assets/4981592/26104309/ef0d612a-3a45-11e7-9d5d-d528f2eed0a7.png">

bower.json:
```

{
  "name": "webexpert",
  "description": "webexpert website",
  "main": "index.html",
  "dependencies": {
    "app-layout": "PolymerElements/app-layout#^2.0.0",
    "app-route": "PolymerElements/app-route#^2.0.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#^2.0.0",
    "iron-icon": "PolymerElements/iron-icon#^2.0.0",
    "iron-icons": "PolymerElements/iron-icons#^2.0.0",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#^2.0.0",
    "iron-localstorage": "PolymerElements/iron-localstorage#^2.0.0",
    "iron-media-query": "PolymerElements/iron-media-query#^2.0.0",
    "iron-pages": "PolymerElements/iron-pages#^2.0.0",
    "iron-selector": "PolymerElements/iron-selector#^2.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#^2.0.0",
    "polymer": "Polymer/polymer#^2.0.0",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0"
  },
  "devDependencies": {
    "web-component-tester": "^6.0.0"
  }
}

```

main view:

```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/app-layout/app-layout.html">
<link rel="import" href="../../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../../bower_components/iron-icon/iron-icon.html">
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">


<dom-module id="webexpert-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <app-drawer-layout>
      <app-drawer opened>
        drawer-content
      </app-drawer>
      <app-header-layout>
        <app-header>
          <app-toolbar>
            <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
            <div main-title>App name</div>
          </app-toolbar>
        </app-header>

        main content

      </app-header-layout>
    </app-drawer-layout>

  </template>

  <script>
    /**
     * @customElement
     * @polymer
     */
    class WebexpertApp extends Polymer.Element {
      static get is() { return 'webexpert-app'; }
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'webexpert-app'
          }
        };
      }
    }

    window.customElements.define(WebexpertApp.is, WebexpertApp);
  </script>
</dom-module>
```

**Comment by bamartin-ua** [comment]
Same here. I feel like this is a bug that should have been caught pre-release...

**Comment by keanulee** [comment]
Please review https://github.com/PolymerElements/app-layout#changes-in-app-layout-20. Specifically, `app-drawer` in `app-drawer-layout` now requires a `slot="drawer"` attribute.

**Comment by bamartin-ua** [comment]
@keanulee yeah, that wasn't my problem.

I can't really make a jsbin recreating it, mostly because jsbin is really broken right now, but for now I'll leave my dev instance up. http://castform.benzetsu.net:8081/

Yes, I have the drawer sliding under the header instead of vise-versa, but I don't think that's the problem, since it was working awesome on #2.0.0-preview.

**Comment by frankiefu** [comment]
@bamartin-ua the link just give us a login screen. Also even if jsbin doesn't work you can still send us a reproducible testcase something like our [demo](https://github.com/PolymerElements/app-layout/blob/master/demo/demo4.html) and we can run it locally.

**Comment by bamartin-ua** [comment]
I am so stupid sometimes. I just spent days getting the login to work right, and then I completely forget about it. 

I have a test account I can share no problem. there's no sensitive data anywhere yet. user:panda pass:polarbear

**Comment by keanulee** [comment]
@bamartin-ua To set the width on `app-drawer`, use `--app-drawer-width` instead of the `--app-drawer-content-container` mixin. Also, you'll need to specify `--app-drawer-width` in the `:host` rule of the my-view1 element (https://github.com/PolymerElements/app-layout/blob/master/app-drawer/app-drawer.html#L48)

**Comment by bamartin-ua** [comment]
interesting. I wasn't setting the width in the mixin, i was setting max-width. I was using --app-drawer-width to set the actual width. so it looks like the change was it's not handling max-width the same as it was. is there any was to specify a maximum width for the app drawer now?

ps why should I set it in the :host rule instead of in an app-drawer rule? shouldn't it be the same so long as the variable scope contains the app-drawer element?

**Comment by vedtam** [comment]
Thanks, sorry for bothering but the samples on webcomponents.org were not updated with the slot attribute, reason for the difficulties, but now I see it got updated.

Thanks!
