### ISSUE TITLE
dropdown within app-header-layout, app-header, app-toolbar displays under main content div

### ISSUE THREAD

**Issue by supermario999** [PolymerElements/app-layout#477]
### Description

When a dropdown is placed in the app-toolbar within an app-header which is within an app-layout-header the dropdown will show as behind the main content div.

I was working with something similar to this combined example: 

```
<app-header-layout>
  <app-header slot="header">
    <app-toolbar>
      <div main-title>App name</div>
	  <div>
		<paper-dropdown-menu label="Dinosaurs">
			<paper-listbox slot="dropdown-content" selected="1">
				<paper-item>allosaurus</paper-item>
				<paper-item>brontosaurus</paper-item>
				<paper-item>carcharodontosaurus</paper-item>
				<paper-item>diplodocus</paper-item>
			</paper-listbox>
		</paper-dropdown-menu>
	  </div>
    </app-toolbar>
  </app-header>
  <div>
    main content
  </div>
</app-header-layout>
```

I noticed the following css being added to the app-layout-header and app-header:

`transform: translate3d(0px, 0px, 0px)`

When this property is removed the dropdown within the app-toolbar correctly comes to the front of the main content div.

### Expected outcome

The dropdown should be in front of the main content div

### Actual outcome

The dropdown is behind the main content div

### Steps to reproduce
1.  Create a page with the example above.
2. Make sure the content within the paper-dropdown is long enough to overlap content in the main content div

### Demo
This is partially setup as jsbin is throwing some errors because of proxy issues I am experiencing.
https://jsbin.com/cecayiyene/1/edit?html,output

### Browsers Affected

- [ X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ X] IE 11
- [ X] IE 10

**Comment by frankiefu** [comment]
The example in your jsbin seems working fine for me.  I had to update to import `web-animations.html` as `paper-dropdown-menu` [not longer includes it by default](https://github.com/PolymerElements/paper-dropdown-menu#changes-in-20). 

jsbin: http://jsbin.com/naxujuduxi/edit?html,output

It's also possible the other styles you have in your app that could cause the issue. For example, if you manually set `overflow: hidden;` on `app-toolbar`, etc. This is because of the stacking context issue. You can read more about it here: https://github.com/PolymerElements/app-layout/issues/279#issuecomment-276169876
