### ISSUE TITLE
Another useless (for neophytes like moi) Polymer tutarticle.

### ISSUE THREAD

**Issue by AbominableIntelligence** [PolymerElements/app-layout#536]
I'll unashamedly admit that I'm new to this.

I also don't feel it's unwarranted to claim that most, if not all, of the Polymer examples are contrived, overly complex and leave out critical information for those of us starting out at the foot of the curve.

So, I see a nice, working app-layout demo. Cool, right? There's even a big code snippet.

So what do I do? I did the bower install bit. Nice, I can see my new bower components directory.

WTF do I do next? Oh, yes! There's a code snippet! Do I copy it into an empty HTML file (which I did, making sure the link refs are correct). There's an import link. Where does it go?

Needless to say I can't get the app-layout demo running, all I see is a gray background with inactive "My App" text in the top left. No buttons, no toolbar, nothing. Must I serve it using "polymer serve"? What gives? I have more unanswered questions, and, perhaps more importantly, _the tuts don't help  create that all-important subtle instinct in knowing what the right questions are to ask in the first place!_

All I want to do is see a running example in my browser without any extraneous crap so I can dig in and learn.

Even the Polymer starter kit stuff is rubbish. Let's build a polymer element using lots of existing polymer element boilerplate in the background! COME ON! How are you supposed to learn anything from that ourobouros clusterf*ck?

It would be nice if the FOSS community as a whole would pull their fingers from their collective arse, consider their audiences and actually made a bit more effort than token articles showing us what's possible while arrogantly assuming that we know what's what.

/rant.

Rhianne

**Comment by keanulee** [comment]
This repo (app-layout) is an element repository, meaning it's laid out so that it can be included as a dependency in an application (such as Polymer Starter Kit).

- When working on _this element_, you need a tool like `polymer serve` to make sure URLs to transitive dependencies work (see https://github.com/Polymer/polyserve/#polyserve).
- When working on an app that _uses_ app-layout (like Polymer Starter Kit), you can use any static web server that serves index.html for all routes, such as [serve](https://www.npmjs.com/package/serve) with `serve -s .` or Polymer CLI with `polymer serve`. The source code of our elements will work in the browser without a compilation step - it just needs to be served at the right URL.

Please refer to the [code of conduct](https://github.com/Polymer/project/blob/master/Code_of_Conduct.md) when engaging with this community.

**Comment by AbominableIntelligence** [comment]
Thanks for the input, Keanu. I must be really dumb, though. I have pored over the contents of the code of conduct and I'm none the wiser as to how I'm supposed to include app-layout as a dependency and to get it running in my browser. I wonder what could be wrong....

You see, I'm not interested in playing nice, I'm interested in playing with toys. If the polymer community is unable to see how its incomplete documentation is a MASSIVE barrier to adoption, then no amount of circle-jerk groupthink and referrals to the code of conduct is going to bring me on board.

Right, I've wasted precisely, lessee, all my time with this abortion of a project - for those of you who know what's what, congratulations. I'll stick with Angular.

**Comment by jarrodek** [comment]
You should lear basics from https://www.polymer-project.org/ website. There's a great description and tutorials of how to start with web components. This repo is one on many components out there and I haven't seen (yet) anyone to put full WC guide to a component documentation. It just makes no sense.
To success with web components you need to understand the basics and study the examples. As with any new technology.
